### ISSUE TITLE
-ansi causing build problems

### ISSUE THREAD

**Issue by phf** [kr/ct#10]
In commit a16b80dedc978df346e9192de77b80ce3b4a90b7 you added -ansi to the CFLAGS which (on my Gentoo box anyway) leads to this:

```
ct/ct.c: In function ‘nstime’:
ct/ct.c:50:5: error: implicit declaration of function ‘clock_gettime’ [-Werror=implicit-function-declaration]
     clock_gettime(CLOCK_MONOTONIC, &t);
     ^
ct/ct.c:50:19: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
     clock_gettime(CLOCK_MONOTONIC, &t);
                   ^
ct/ct.c:50:19: note: each undeclared identifier is reported only once for each function it appears in
ct/ct.c: In function ‘tmpfd’:
ct/ct.c:151:5: error: implicit declaration of function ‘fileno’ [-Werror=implicit-function-declaration]
     return fileno(f);
     ^
ct/ct.c: In function ‘waittest’:
ct/ct.c:168:5: error: implicit declaration of function ‘wait3’ [-Werror=implicit-function-declaration]
     pid = wait3(&stat, 0, 0);
     ^
ct/ct.c:172:5: error: implicit declaration of function ‘killpg’ [-Werror=implicit-function-declaration]
     killpg(pid, 9);
     ^
ct/ct.c: In function ‘start’:
ct/ct.c:195:5: error: implicit declaration of function ‘mktemp’ [-Werror=implicit-function-declaration]
     mktemp(t->dir);
     ^
```

If I leave out -ansi everything works fine again. Since your Makefile is only an example I guess it's only a half-issue, I'd just worry that this build failure might turn someone away who doesn't have the time to investigate. (The other alternative is to add some feature test macros BTW, then you can leave -ansi in place.) I guess I also wonder why -ansi is essential by default?

**Comment by phf** [comment]
Just double-checked, if you want to keep "-ansi" then "-D_DEFAULT_SOURCE" would solve the problem as well. But again, I doubt it should say "-ansi" in the first place.

**Comment by phf** [comment]
Can't stop myself today. Note that if you added "-ansi" to ensure that code works on platforms with older compilers, you would need to say "-Wpedantic" as well. If you do, you'll see that there's code in ct that doesn't work before C99 (errors refer to "anonymous variadic macros" for example). As far as I can tell, the "best" default flags for the example Makefile (the flags making the clearest statement about what kind of code this is) would be these:

-std=c99 -D_DEFAULT_SOURCE -Werror -Wall -Wextra -Wpedantic -Wwrite-strings -Wformat=2

**Comment by fhfuwei** [comment]
@phf thanks for explanation. Save my time.
