### ISSUE TITLE
ctcheck should have an option to output benchmarks only

### ISSUE THREAD

**Issue by ysmolsky** [kr/ct#25]
Right now`_ctcheck` outputs tests results as well. But I propose it to return just the benchmarks to allow measuring with `benchstat`. It should be allowed to run benchmark suite N times too.

_Originally posted by in https://github.com/beanstalkd/beanstalkd/pull/506#issuecomment-515756418_

**Comment by ysmolsky** [comment]
Hmm, just tried this version and it is not so handy when I write some code that timeouts or behaves slow in tests. I have no indication of the progress... It would be better to keep the progress and completely disable testing in the case of -bench or some different switch. Sorry for not making myself clear before.

**Comment by ysmolsky** [comment]
I can disable testing this way: 
```ct/_ctcheck -test '' -bench '*'```

**Comment by kr** [comment]
Yeah, if you want to skip the tests it’s best to use `-test ''`.

I don’t want `-b` or `-bench` to affect which tests will run. Tests and benchmarks imo should be controlled orthogonally.

**Comment by kr** [comment]
(Or of course you can use `-test .` or any other baue that matches none of the test names.)

**Comment by kr** [comment]
Would you prefer I revert 80f01552bd042dbc80c118a42e90545792900bd3 then? I’m happy either way on that.

**Comment by ysmolsky** [comment]
Yes, please, revert would be the most wanted.
